server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
        - id: data-service
          uri: lb://data-service
          predicates:
            - Path=/api/data/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
